dist: xenial
sudo: required
language: node_js
jdk: oraclejdk8
node_js:
  - "8"
addons:
  chrome: stable
  apt:
    packages:
      - oracle-java8-installer  
script:
  - jdk_switcher use oraclejdk8  
install: "npm install"
cache:
  directories:
    - node_modules
notifications:
  email: false
