dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --no-sandbox #--headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - #export DISPLAY=:99.0
  - #sh -e /etc/init.d/xvfb start
  - #sleep 3  
install: "npm install"
cache:
  directories:
    - node_modules
notifications:
  email: false
