dist: xenial
sudo: required
language: node_js
jdk: oraclejdk8
node_js:
  - "8"
addons:
  chrome: stable
before_install:
  - jdk_switcher use oraclejdk8  
install: "npm install"
cache:
  directories:
    - node_modules
notifications:
  email: false
