dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
addons:
  chrome: stable
before_script:
  rm -rf ./node_modules package-lock.json
  npm install
install: "npm install"
cache:
  directories:
    - node_modules
notifications:
  email: false
