dist: xenial
sudo: required
language: node_js
node_js:
  - "8"
before_install:
  - npm install -g npm'@5.6.0'
addons:
  chrome: stable
install: "npm install"
cache:
  directories:
    - node_modules
notifications:
  email: false
